# Workflow API version
apiVersion: io.orquestra.workflow/1.0.0

# Prefix for workflow ID
name: ml-1-workflow

# List components needed by workflow.
imports:
- name: sklearn-component
  type: git
  parameters:
    repository: "git@github.com:zapatacomputing/tutorial-orquestra-sklearn.git"
    branch: "master"

steps:

# This step runs the step that trains the model
- name: perceptron-training
  config:
    runtime:
      language: python3
      imports: [sklearn-component]
      parameters:
        file: sklearn-component/steps/ml_tutorial_1_step.py
        function: generate_train_step
  inputs:
    - dataset_name: "simple_dataset"
      type: string
    - model_name: "perceptron"
      type: string
  outputs:
  - name: result
    type: output_type

types:
 - output_type